export const FocusSproutStrings =
{
    AppName: 'Focus Sprout',
    FocusMode: '집중 시간',
    BreakMode: '휴식 시간',
    Settings: '설정',
    StartFocus: '집중 시작',
    StartBreak: '휴식 시작',
    Pause: '잠시 멈춤',
    Resume: '이어서 시작',
    Reset: '초기화',
    TodayGrowth: '오늘의 성장',
    SessionsCompleted: (Count: number) => `${Count}회 집중 완료`,
    GoalProgress: (Completed: number, Goal: number) => `오늘 목표 ${Completed}/${Goal}`,
    EncouragementStart: '첫 집중으로 새싹을 깨워보세요.',
    EncouragementGrowing: '좋은 흐름이에요. 계속 자라고 있어요.',
    EncouragementComplete: '오늘의 정원이 활짝 자랐어요!',
    TimerSettings: '타이머 설정',
    FocusMinutes: '집중 시간 (분)',
    BreakMinutes: '휴식 시간 (분)',
    MinutesHint: '1분에서 60분 사이로 설정할 수 있어요.',
    Cancel: '취소',
    Save: '저장',
    ResetTitle: '타이머를 초기화할까요?',
    ResetDescription: '현재 진행 중인 시간이 처음으로 돌아갑니다.',
    KeepFocusing: '계속 집중',
    ConfirmReset: '초기화',
    TimerError: '타이머 상태를 불러오지 못했어요. 다시 시도해 주세요.',
    SettingsError: '시간은 1분에서 60분 사이여야 해요.',
    Loading: '정원을 준비하고 있어요.',
} as const;
